### ISSUE TITLE
Unique constraint (in schema) is not working

### ISSUE THREAD

**Issue by scrybbler** [theodi/csvlint#183]
Uniqueness is not being tested, apparently.

Here are my csv and schema respectively:
https://drive.google.com/file/d/0B3CDKorSOdGNNm1CbXFrUmlFY1U/view?usp=sharing
https://drive.google.com/file/d/0B3CDKorSOdGNN3JlZ2pDLWNKaXc/view?usp=sharing

The constraint is violated on lines 3 & 5 (column 1) and 4 & 12 (column 8) of the data. Those pairs are the lines where data is repeated.

The validator reports no errors or warnings on those data columns.

**Comment by scrybbler** [comment]
![csv lint validation results](https://cloud.githubusercontent.com/assets/12719803/7945796/a0ae19c4-0938-11e5-8fac-0b44ee64391d.png)

**Comment by ldodds** [comment]
Hi @scrybbler, I've just taken a quick look at this. The constraint isn't being applied because the application is failing to correctly parse your JSON schema.

Currently if it fails to load a schema it just falls back to processing the file without, this is something that we should probably change.

If you paste your schema into http://jsonlint.com/ you'll see that its not valid JSON. I found that there were several extra brackets, and a stray comma.

The regular expression that matches the home page URL is also invalid, the asterisk character means "zero or more" but because its at the start of the regular expression, the parser doesn't know what its matching. The slash and ? characters also need to be escaped.

Once I'd correct those and tried the schema again, it correctly reports several unique constraints.

Can I ask you to retest with a fixed schema? Here's the version I used locally: https://gist.github.com/ldodds/b0ae664e623ec62f595c

**Comment by ldodds** [comment]
btw, this is a useful service for testing regular expressions: http://rubular.com/

**Comment by scrybbler** [comment]
Leigh, 

Thank you! I was worried that it was something like this, but couldn't tell due to issue #186.

Yes, I retested with your schema and am getting much better results.

**Comment by scrybbler** [comment]
I should mention that I did attempt to validate my JSON at a different site, but that's what I get for trusting the internet...

**Comment by scrybbler** [comment]
Closed - schema error.
